"""Ambient-documentation corpus: download the public sources, rebuild the 577-encounter cohort, splice insertions.

Sources (both CC BY 4.0):
  * ACI-Bench (Yim et al., Sci. Data 2023): the ``aci``-source rows of the official validation set (11) and the
    three test sets (22 each) = 77 encounters. Train rows and the virtassist/virtscribe sources are not used.
  * MTS-Dialog (Ben Abacha et al., EACL 2023): TestSet-1 (200), TestSet-2 (200), ValidationSet (100) = 500
    section-level encounters; the reference note is the section text.
The inserted exchanges generated by GPT-5.4 are frozen in data/ambient/insertions.parquet and spliced into the clean
transcripts after the turn chosen by the generator, in the transcript's own speaker-label style (``insert_conversation``).

    python -m llm_distract.ambient.data --download data/ambient/sources
    python -m llm_distract.ambient.data --build data/ambient/pairs.parquet
"""
from __future__ import annotations

import argparse
import re
import urllib.request
from pathlib import Path

import pandas as pd

ACI_BASE = "https://raw.githubusercontent.com/wyim/aci-bench/main/data/challenge_data/"
ACI_FILES = {"valid": "valid.csv", "test1": "clinicalnlp_taskB_test1.csv", "test2": "clinicalnlp_taskC_test2.csv",
             "test3": "clef_taskC_test3.csv"}
MTS_BASE = "https://raw.githubusercontent.com/abachaa/MTS-Dialog/main/Main-Dataset/"
MTS_FILES = {"mts_dialog_test1": "MTS-Dialog-TestSet-1-MEDIQA-Chat-2023.csv",
             "mts_dialog_test2": "MTS-Dialog-TestSet-2-MEDIQA-Sum-2023.csv",
             "mts_dialog_valid": "MTS-Dialog-ValidationSet.csv"}
# The HF mirror that the original pipeline read folded four Unicode punctuation marks to ASCII.
ASCII_FOLD = str.maketrans({"’": "'", "“": '"', "”": '"', "–": "-"})
SPEAKER_TAG_RE = re.compile(r"^\s*([A-Za-z][A-Za-z0-9_ -]{0,40}):", re.MULTILINE)
BRACKET_TAG_RE = re.compile(r"^\s*\[([a-z][a-z0-9_]*)\]", re.MULTILINE)   # ACI-Bench style: [doctor] / [patient]
TURN_RE = re.compile(r"^\s*(?:\[[a-z][a-z0-9_]*\]|[A-Za-z][A-Za-z0-9_ -]{0,40}:)")
SPLITS = ("aci_bench_test", "aci_bench_valid", "mts_dialog_test1", "mts_dialog_test2", "mts_dialog_valid")


def download_sources(dest: str | Path) -> dict:
    """Fetch the seven source CSVs into ``dest`` (skips files that already exist)."""
    dest = Path(dest)
    dest.mkdir(parents=True, exist_ok=True)
    paths = {}
    for split, fname in ACI_FILES.items():
        paths[f"aci_{split}"] = _fetch(ACI_BASE + fname, dest / fname)
    for split, fname in MTS_FILES.items():
        paths[split] = _fetch(MTS_BASE + fname, dest / fname)
    return paths


def _fetch(url: str, path: Path) -> Path:
    if not path.exists():
        urllib.request.urlretrieve(url, path)
    return path


def build_cohort(sources: str | Path) -> pd.DataFrame:
    """The 577 clean encounters: source_dataset, item_id, clean_transcript, reference_note, family."""
    sources = Path(sources)
    rows = []
    for split, fname in ACI_FILES.items():
        df = pd.read_csv(sources / fname)
        df = df[df["dataset"] == "aci"]
        for _, r in df.iterrows():
            rows.append({"source_dataset": "aci_bench_valid" if split == "valid" else "aci_bench_test",
                         "aci_split": split, "item_id": str(r["encounter_id"]),
                         "clean_transcript": str(r["dialogue"]).translate(ASCII_FOLD),
                         "reference_note": str(r["note"]).translate(ASCII_FOLD), "family": "ACI-Bench"})
    for split, fname in MTS_FILES.items():
        df = pd.read_csv(sources / fname)
        for _, r in df.iterrows():
            rows.append({"source_dataset": split, "aci_split": "", "item_id": str(r["ID"]),
                         "clean_transcript": str(r["dialogue"]), "reference_note": str(r["section_text"]),
                         "family": "MTS-Dialog"})
    out = pd.DataFrame(rows)
    counts = out["source_dataset"].value_counts().to_dict()
    expected = {"aci_bench_test": 66, "aci_bench_valid": 11, "mts_dialog_test1": 200, "mts_dialog_test2": 200, "mts_dialog_valid": 100}
    if counts != expected:
        raise RuntimeError(f"unexpected cohort sizes {counts}")
    return out


def speaker_tags(transcript: str) -> list:
    """Speaker tags shown to the insertion generator (``Doctor``/``Patient`` when no ``Tag:`` lines match, e.g. ACI-Bench)."""
    tags = list(dict.fromkeys(m.group(1).strip() for m in SPEAKER_TAG_RE.finditer(transcript)))
    return tags or ["Doctor", "Patient"]


def conform_labels(conversation: str, transcript: str) -> str:
    """Rewrite the exchange's ``Doctor:``/``Patient:`` labels into the transcript's bracketed lowercase style.

    ACI-Bench transcripts label turns ``[doctor]``/``[patient]`` whereas the frozen insertions were generated with
    ``Doctor:``/``Patient:`` labels; without this step the exchange would be the only differently formatted turn.
    Transcripts without bracketed labels (MTS-Dialog) are returned unchanged.
    """
    if not BRACKET_TAG_RE.search(transcript):
        return conversation
    out = []
    for line in conversation.splitlines():
        m = SPEAKER_TAG_RE.match(line)
        out.append(f"[{m.group(1).strip().lower().replace(' ', '_')}]{line[m.end():]}" if m else line)
    return "\n".join(out)


def insert_conversation(transcript: str, conversation: str, insert_after_turn: int) -> str:
    """Splice the exchange after the ``insert_after_turn``-th turn (1 = after the first turn).

    Turns are lines that start with a ``Tag:`` or ``[tag]`` speaker label; the exchange is relabelled to the
    transcript's style first (``conform_labels``). A transcript without labelled turns receives the exchange after
    its final line.
    """
    transcript = str(transcript).strip()
    conversation = str(conversation).strip()
    if not transcript:
        return conversation
    if not conversation:
        return transcript
    conversation = conform_labels(conversation, transcript)
    lines = transcript.splitlines()
    turn_idx = [i for i, line in enumerate(lines) if TURN_RE.match(line)]
    if not turn_idx:
        return f"{transcript}\n{conversation}"
    turn = min(max(1, int(insert_after_turn)), len(turn_idx))
    cut = turn_idx[turn] if turn < len(turn_idx) else len(lines)
    return "\n".join(lines[:cut] + [conversation] + lines[cut:])


def build_pairs(cohort: pd.DataFrame, insertions: pd.DataFrame) -> pd.DataFrame:
    """One row per (encounter, distractor type) with clean and distracted transcripts."""
    ins = insertions.copy()
    ins["item_id"] = ins["item_id"].astype(str)
    df = ins.merge(cohort, on=["source_dataset", "item_id"], how="left", validate="many_to_one")
    if df["clean_transcript"].isna().any():
        missing = df[df["clean_transcript"].isna()][["source_dataset", "item_id"]].head()
        raise RuntimeError(f"insertions without a matching encounter, e.g. {missing.to_dict('records')}")
    df["distracted_transcript"] = [insert_conversation(t, c, k) for t, c, k in
                                   zip(df["clean_transcript"], df["distractor_conversation"], df["insert_after_turn"])]
    cols = ["source_dataset", "family", "item_id", "distractor_type", "clean_transcript", "distracted_transcript",
            "reference_note", "distractor_conversation", "insert_after_turn", "distractor_summary", "distractor_topic",
            "generation_model"]
    return df[cols]


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--sources", default="data/ambient/sources", help="directory for the downloaded CSVs")
    ap.add_argument("--insertions", default="data/ambient/insertions_v3.parquet")
    ap.add_argument("--download", action="store_true", help="download the ACI-Bench and MTS-Dialog CSVs")
    ap.add_argument("--build", metavar="OUT", help="write clean/distracted transcript pairs to this parquet")
    args = ap.parse_args()
    if args.download:
        paths = download_sources(args.sources)
        print("downloaded", len(paths), "files to", args.sources)
    if args.build:
        cohort = build_cohort(args.sources)
        pairs = build_pairs(cohort, pd.read_parquet(args.insertions))
        Path(args.build).parent.mkdir(parents=True, exist_ok=True)
        pairs.to_parquet(args.build, index=False)
        print(f"wrote {len(pairs)} transcript pairs for {cohort.shape[0]} encounters to {args.build}")


if __name__ == "__main__":
    main()
